name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Ameer-Saqer

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate pacman graph"
          branch: main
          push_options: --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
